/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as CookRouteImport } from './routes/cook'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DishesIndexRouteImport } from './routes/dishes.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as DishesSlugRouteImport } from './routes/dishes.$slug'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiSuggestRecipesRouteImport } from './routes/api/suggest-recipes'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const CookRoute = CookRouteImport.update({
  id: '/cook',
  path: '/cook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DishesIndexRoute = DishesIndexRouteImport.update({
  id: '/dishes/',
  path: '/dishes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const DishesSlugRoute = DishesSlugRouteImport.update({
  id: '/dishes/$slug',
  path: '/dishes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestRecipesRoute = ApiSuggestRecipesRouteImport.update({
  id: '/api/suggest-recipes',
  path: '/api/suggest-recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cook': typeof CookRoute
  '/pantry': typeof PantryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/suggest-recipes': typeof ApiSuggestRecipesRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/dishes/$slug': typeof DishesSlugRoute
  '/chat/': typeof ChatIndexRoute
  '/dishes/': typeof DishesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cook': typeof CookRoute
  '/pantry': typeof PantryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/suggest-recipes': typeof ApiSuggestRecipesRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/dishes/$slug': typeof DishesSlugRoute
  '/chat': typeof ChatIndexRoute
  '/dishes': typeof DishesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cook': typeof CookRoute
  '/pantry': typeof PantryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/suggest-recipes': typeof ApiSuggestRecipesRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/dishes/$slug': typeof DishesSlugRoute
  '/chat/': typeof ChatIndexRoute
  '/dishes/': typeof DishesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cook'
    | '/pantry'
    | '/api/chat'
    | '/api/suggest-recipes'
    | '/chat/$threadId'
    | '/dishes/$slug'
    | '/chat/'
    | '/dishes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cook'
    | '/pantry'
    | '/api/chat'
    | '/api/suggest-recipes'
    | '/chat/$threadId'
    | '/dishes/$slug'
    | '/chat'
    | '/dishes'
  id:
    | '__root__'
    | '/'
    | '/cook'
    | '/pantry'
    | '/api/chat'
    | '/api/suggest-recipes'
    | '/chat/$threadId'
    | '/dishes/$slug'
    | '/chat/'
    | '/dishes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookRoute: typeof CookRoute
  PantryRoute: typeof PantryRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSuggestRecipesRoute: typeof ApiSuggestRecipesRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  DishesSlugRoute: typeof DishesSlugRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DishesIndexRoute: typeof DishesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook': {
      id: '/cook'
      path: '/cook'
      fullPath: '/cook'
      preLoaderRoute: typeof CookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dishes/': {
      id: '/dishes/'
      path: '/dishes'
      fullPath: '/dishes/'
      preLoaderRoute: typeof DishesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dishes/$slug': {
      id: '/dishes/$slug'
      path: '/dishes/$slug'
      fullPath: '/dishes/$slug'
      preLoaderRoute: typeof DishesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest-recipes': {
      id: '/api/suggest-recipes'
      path: '/api/suggest-recipes'
      fullPath: '/api/suggest-recipes'
      preLoaderRoute: typeof ApiSuggestRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookRoute: CookRoute,
  PantryRoute: PantryRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSuggestRecipesRoute: ApiSuggestRecipesRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  DishesSlugRoute: DishesSlugRoute,
  ChatIndexRoute: ChatIndexRoute,
  DishesIndexRoute: DishesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
